name: Build docker image
on:
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  CARGO_TERM_COLOR: always
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: downcase REPO
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >>${GITHUB_ENV}

      - uses: whoan/docker-build-with-cache-action@v8
        with:
          username: ${{ github.actor }}
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: ${{ env.REGISTRY }}
          image_name: ${{ env.IMAGE_NAME }}
          push_image_and_stages: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
